export const WALKTHROUGH_TIMING = {
  STEP_8_AUTO_COMPLETE_DELAY: 2000, // ms
  SKIP_ANIMATION_DURATION: 200, // ms
  STEP_8_COMPLETION_DELAY: 500, // ms
  STATE_PROPAGATION_DELAY: 0, // ms
} as const;

